---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: trailing-whitespace

- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0']

- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    exclude: tests_.*.py|version.*.py|setup.py     # ignore tests and versioneer related code

- repo: https://github.com/ikamensh/flynt/
  rev: 1.0.1
  hooks:
  - id: flynt

- repo: https://github.com/asottile/reorder-python-imports
  rev: v3.11.0
  hooks:
  - id: reorder-python-imports
    args: [--py37-plus]

- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v2.4.0
  hooks:
  - id: setup-cfg-fmt

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.1
  hooks:
  - id: mypy
    additional_dependencies: [types-all, pydantic]
    files: bidsmreye
    args: [--config-file, pyproject.toml]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.11.0
  hooks:
  - id: pyupgrade
    args: [--py37-plus]

# - repo: https://github.com/snakemake/snakefmt
#   rev: v0.8.0
#   hooks:
#   - id: snakefmt
#     args: [bidsgnostic/workflow/Snakefile]
