---
version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:

  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - run:
        name: build docker image
        command: |
          git describe --tags --always > version
          docker build -t "bids/${CIRCLE_PROJECT_REPONAME,,}" .
          mkdir -p "${HOME}/docker"
          docker save "bids/${CIRCLE_PROJECT_REPONAME,,}" > "${HOME}/docker/image.tar"
    - persist_to_workspace:
        root: /home/circleci
        paths:
        - docker/image.tar


  get_external_data:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - restore_cache:
        keys:
        - my_cache
    - run:
        name: Get test data ds114_test1
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/utils/get_data_from_osf.sh
          bash get_data_from_osf.sh ds114_test1
          bash get_data_from_osf.sh ds114_test2
    - save_cache:
        key: my_cache
        paths:
        - ~/data
    - persist_to_workspace:
        root: /home/circleci
        paths:
        - data/ds114_test1
        - data/ds114_test2


  test_internal_data:
    executor: python/default
    steps:
    - checkout
    - run: pip install -e .
    - run:
        name: test internal data at participant level
        command: |
          mkdir tmp
          cd tmp
          bidsgnostic ../tests/data/ds001 results participant -c24 --verbose --log_level 2
    - run:
        name: test internal data at group level
        command: |
          cd tmp
          bidsgnostic ../tests/data/ds001 results group -c24 --verbose --log_level 2


  test_external_data:
    executor: python/default
    parameters:
      dataset:
        type: string
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - checkout
    - run: pip install -e .
    - run:
        name: test external ds114_<< parameters.dataset >> at participant level
        command: |
          bidsgnostic \
            /tmp/workspace/data/ds114_test<< parameters.dataset >> \
            outputs<< parameters.dataset >> \
            participant \
            -c2 --verbose --log_level 2 \
            --participant-label 01 02
    # - run:
    #     name: test external data ds114_<< parameters.dataset >> at group level
    #     command: |
    #       bidsgnostic \
    #         /tmp/workspace/data/ds114_test<< parameters.dataset >> \
    #         outputs<< parameters.dataset >> \
    #         group \
    #         -c2 --verbose --log_level 2


  test_docker:
    machine:
      image: ubuntu-2204:2022.10.2

    parameters:
      dataset:
        type: string

    steps:

    - run: sudo apt-get update -qq && sudo apt-get install -y -qq tree

    - attach_workspace:
        at: /tmp/workspace
    - run: docker load -i /tmp/workspace/docker/image.tar

    - run: mkdir -p ${HOME}/outputs_docker_<< parameters.dataset >>

    - run:
        name: participant level analysis ds114_test<< parameters.dataset >>
        command: |
          docker run -ti --rm \
            -v /tmp/workspace/data/ds114_test<< parameters.dataset >>:/bids_dataset \
            -v ${HOME}/outputs_docker_<< parameters.dataset >>:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset \
                /outputs participant \
                -c1 --verbose --log_level 2 \
                --participant_label 01 02
    # - run:
    #     name: group level analysis ds114_test<< parameters.dataset >>
    #     command: |
    #       docker run -ti --rm \
    #         -v /tmp/workspace/data/ds114_test<< parameters.dataset >>:/bids_dataset \
    #         -v ${HOME}/outputs_docker_<< parameters.dataset >>:/outputs \
    #           bids/${CIRCLE_PROJECT_REPONAME,,} \
    #             /bids_dataset \
    #             /outputs group \
    #             -c1 --verbose --log_level 2

    - run:
        name: list results
        command: tree ${HOME}/outputs_docker_<< parameters.dataset >>

    - store_artifacts:
        path: ~/outputs_docker_<< parameters.dataset >>


workflows:
  build_test_deploy:
    jobs:
    - get_external_data
    - test_internal_data
    - build:
        requires:
        - test_internal_data
        - test_external_data
    - test_external_data:
        requires:
        - get_external_data
        matrix:
          parameters:
            dataset: ['1', '2']
    - test_docker:
        requires:
        - build
        - get_external_data
        matrix:
          parameters:
            dataset: ['1', '2']
