---
version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:

  test_internal_data:
    executor: python/default
    steps:
    - checkout
    - run: pip install -e .
    - run: bidsgnostic tests/data/ds001 results participant -c24

  test_external_data:
    executor: python/default
    parameters:
      dataset:
        type: string
    steps:
    - checkout
    - run: pip install -e .
    - restore_cache:
        keys:
        - my_cache
    - run:
        name: Get test data ds114_test<< parameters.dataset >>
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/get_ds114_test<< parameters.dataset >>.sh
          bash get_ds114_test<< parameters.dataset >>.sh

    - run: bidsgnostic data/ds114_test<< parameters.dataset >> results participant -c24
    - run: bidsgnostic data/ds114_test2 results participant -c24
    - save_cache:
        key: my_cache
        paths:
        - ~/data

workflows:
  build_test_deploy:
    jobs:
    - test_internal_data
    - test_external_data:
        matrix:
          parameters:
            dataset: ['1', '2']
