---
version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - run:
        name: Build Docker image
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/build_docker.sh
          bash build_docker.sh
    - persist_to_workspace:
        root: /home/circleci
        paths:
        - docker/image.tar

  get_external_data:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - restore_cache:
        keys:
        - my_cache
    - run:
        name: Get test data ds114_test1
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/utils/get_data_from_osf.sh
          bash get_data_from_osf.sh ds114_test1
          bash get_data_from_osf.sh ds114_test2
    - save_cache:
        key: my_cache
        paths:
        - ~/data
    - persist_to_workspace:
        root: /home/circleci
        paths:
        - data/ds114_test1
        - data/ds114_test2

  test_internal_data:
    executor: python/default
    parameters:
      dataset:
        type: string
    steps:
    - run: sudo apt-get update -qq && sudo apt-get install -y -qq tree
    - checkout
    - run: git submodule update --init --recursive && git submodule update --recursive
    - run: pip install -e .
    - run:
        name: test errors on internal data at participant level
        command: |
          mkdir tmp
          cd tmp
          # cannot be tested yet
          # bidsgnostic ../tests/data/bids-examples/ds001 results_<< parameters.dataset >> participant && \
          #   --cores all --verbose --log_level 2 --participant_label 666
          bidsgnostic ../tests/data/bids-examples/<< parameters.dataset >> \
            results_<< parameters.dataset >> participant \
            --cores all --verbose --log_level 2 --include_events foo
    - run:
        name: test happy path on internal data at participant level
        command: |
          cd tmp
          bidsgnostic ../tests/data/bids-examples/<< parameters.dataset >> \
            results_<< parameters.dataset >> participant \
            --cores all --verbose --log_level 2 --participant_label 01 02
          bidsgnostic ../tests/data/bids-examples/<< parameters.dataset >> \
            results_<< parameters.dataset >> participant \
            --cores all --verbose --log_level 2 --include_events pumps_demean
          bidsgnostic ../tests/data/bids-examples/<< parameters.dataset >> \
            results_<< parameters.dataset >> participant \
            --cores all --verbose --log_level 2
    - run:
        name: test errors on internal data at group level
        command: |
          cd tmp
          bidsgnostic_layout ../tests/data/bids-examples/<< parameters.dataset >> \
            results_<< parameters.dataset >> group \
            --log_level 2 --participant_label 01 02
          bidsgnostic_layout ../tests/data/bids-examples/<< parameters.dataset >> \
            results_<< parameters.dataset >> group \
            --log_level 2 --participant_label 666
    - run:
        name: test happy path on internal data at group level
        command: |
          cd tmp
          bidsgnostic_layout ../tests/data/bids-examples/<< parameters.dataset >> \
            results_<< parameters.dataset >> group \
            --log_level 2 --participant_label 01 02
          bidsgnostic_layout ../tests/data/bids-examples/<< parameters.dataset >> \
            results_<< parameters.dataset >> group \
            --log_level 2 --plot_by suffix
          bidsgnostic_layout ../tests/data/bids-examples/<< parameters.dataset >> \
            results_<< parameters.dataset >> group  \
            --log_level 2
    - run:
        name: list results << parameters.dataset >>
        command: tree tmp/results_<< parameters.dataset >>

  test_data_event_column:
    executor: python/default
    steps:
    - run: sudo apt-get update -qq && sudo apt-get install -y -qq tree
    - checkout
    - run: git submodule update --init --recursive && git submodule update --recursive
    - run: pip install -e .
    - run:
        name: test happy path on internal data at participant level
        command: |
          mkdir tmp
          cd tmp
          bidsgnostic ../tests/data/bids-examples/fnirs_automaticity \
            results_fnirs_automaticity participant \
            --event_column event_type \
            --cores all --verbose --log_level 2
    - run:
        name: list results fnirs_automaticity
        command: tree tmp/results_fnirs_automaticity

  test_external_data:
    executor: python/default
    parameters:
      dataset:
        type: string
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: sudo apt-get update -qq && sudo apt-get install -y -qq tree
    - checkout
    - run: pip install -e .
    - run:
        name: test external ds114_<< parameters.dataset >> at participant level
        command: |
          bidsgnostic \
            /tmp/workspace/data/ds114_test<< parameters.dataset >> \
            outputs<< parameters.dataset >> \
            participant \
            -c2 --verbose --log_level 2 \
            --participant_label 01 02

    - run:
        name: test external data ds114_<< parameters.dataset >> at group level
        command: |
          bidsgnostic_layout \
            /tmp/workspace/data/ds114_test<< parameters.dataset >> \
            outputs<< parameters.dataset >> \
            group \
            --log_level 2

    - run:
        name: list results
        command: tree outputs<< parameters.dataset >>

    - store_artifacts:
        path: ~/outputs<< parameters.dataset >>

  test_docker:
    machine:
      image: ubuntu-2204:2022.10.2

    parameters:
      dataset:
        type: string

    steps:
    - run: sudo apt-get update -qq && sudo apt-get install -y -qq tree

    - attach_workspace:
        at: /tmp/workspace
    - run: docker load -i /tmp/workspace/docker/image.tar

    - run: mkdir -p ${HOME}/outputs_docker_<< parameters.dataset >>

    - run:
        name: version
        command: |
          docker run -ti --rm \
            -v /tmp/workspace/data/ds114_test<< parameters.dataset >>:/bids_dataset \
            -v ${HOME}/outputs_docker_<< parameters.dataset >>:/outputs \
              remi-gau/bidsgnostic \
                /bids_dataset \
                /outputs participant --version

    - run:
        name: participant level analysis ds114_test<< parameters.dataset >>
        command: |
          docker run -ti --rm \
            -v /tmp/workspace/data/ds114_test<< parameters.dataset >>:/bids_dataset \
            -v ${HOME}/outputs_docker_<< parameters.dataset >>:/outputs \
              remi-gau/bidsgnostic \
                /bids_dataset \
                /outputs participant \
                -c1 --verbose --log_level 2 \
            --participant_label 01 02

        # - run:
        #     name: group level analysis ds114_test<< parameters.dataset >>
        #     command: |
        #       docker run -ti --rm \
        #         -v /tmp/workspace/data/ds114_test<< parameters.dataset >>:/bids_dataset \
        #         -v ${HOME}/outputs_docker_<< parameters.dataset >>:/outputs \
        #           remi-gau/bidsgnostic \
        #             /bids_dataset \
        #             /outputs group \
        #             -c1 --verbose --log_level 2

    - run:
        name: list results
        command: tree ${HOME}/outputs_docker_<< parameters.dataset >>

    - store_artifacts:
        path: ~/outputs_docker_<< parameters.dataset >>

workflows:
  build_test_deploy:
    jobs:
    - get_external_data
    - test_data_event_column
    - test_internal_data:
        matrix:
          parameters:
            dataset: [ds001]
    - build:
        requires:
        - test_internal_data
        - test_external_data
    - test_external_data:
        requires:
        - get_external_data
        matrix:
          parameters:
            dataset: ['1', '2']
    - test_docker:
        requires:
        - build
        - get_external_data
        - test_data_event_column
        matrix:
          parameters:
            dataset: ['1', '2']
# VS Code Extension Version: 1.5.1
