---
version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:

  build:
    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - run:
        name: build docker image
        command: |
          if [[ -e "${HOME}/docker/image.tar" ]]; then
              docker load -i "${HOME}/docker/image.tar"
          fi
          git describe --tags --always > version
          docker build -t "bids/${CIRCLE_PROJECT_REPONAME,,}" .
          mkdir -p "${HOME}/docker"
          docker save "bids/${CIRCLE_PROJECT_REPONAME,,}" > "${HOME}/docker/image.tar"
    - persist_to_workspace:
        root: /home/circleci
        paths:
        - docker/image.tar

  get_external_data:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - restore_cache:
        keys:
        - my_cache
    - run:
        name: Get test data ds114_test1
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/get_ds114_test1.sh
          bash get_ds114_test1.sh
    - run:
        name: Get test data ds114_test2
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/get_ds114_test2.sh
          bash get_ds114_test2.sh
    - save_cache:
        key: my_cache
        paths:
        - ~/data
    - persist_to_workspace:
        root: /home/circleci
        paths:
        - data/ds114_test1
        - data/ds114_test2

  test_internal_data:
    executor: python/default
    steps:
    - checkout
    - run: pip install -e .
    - run: bidsgnostic tests/data/ds001 results participant -c24

  test_external_data:
    executor: python/default
    parameters:
      dataset:
        type: string
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - checkout
    - run: pip install -e .
    - run:
        name: test external data ds114_test<< parameters.dataset >>
        command: |
          bidsgnostic \
            /tmp/workspace/data/ds114_test<< parameters.dataset >> \
            outputs<< parameters.dataset >> \
            participant \
            --participant-label 01 \
            -c24


workflows:
  build_test_deploy:
    jobs:
    - build
    - get_external_data
    - test_internal_data
    - test_external_data:
        requires:
        - get_external_data
        matrix:
          parameters:
            dataset: ['1', '2']
