---
version: 2.1

jobs:

  test_internal_data:
    machine:
      image: 3.11.1-bullseye
    steps:
    - checkout
    - run: pip install -e .
    - run: bidsgnostic tests/data/ds001 results participant -c24

  test_external_data:
    machine:
      image: 3.11.1-bullseye
    parameters:
      dataset:
        type: string
    steps:
    - checkout
    - run: pip install -e .
    - restore_cache:
        keys:
        - my_cache
    - run:
        name: Get test data ds114_test<< parameters.dataset >>
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/get_ds114_test<< parameters.dataset >>.sh
          bash get_ds114_test<< parameters.dataset >>.sh

    - run: bidsgnostic data/ds114_test<< parameters.dataset >> results participant -c24
    - run: bidsgnostic data/ds114_test2 results participant -c24


workflows:
  build_test_deploy:
    jobs:
    - test_internal_data
    - test_external_data:
        matrix:
          parameters:
            dataset: ['1', '2']
